/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spade_reporter_Audit_SYSCALL */

#ifndef _Included_spade_reporter_Audit_SYSCALL
#define _Included_spade_reporter_Audit_SYSCALL
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
