/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spade_reporter_Audit */

#ifndef _Included_spade_reporter_Audit
#define _Included_spade_reporter_Audit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     spade_reporter_Audit
 * Method:    initAuditStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_spade_reporter_Audit_initAuditStream
  (JNIEnv *, jclass);

/*
 * Class:     spade_reporter_Audit
 * Method:    readAuditStream
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_spade_reporter_Audit_readAuditStream
  (JNIEnv *, jclass);

/*
 * Class:     spade_reporter_Audit
 * Method:    closeAuditStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_spade_reporter_Audit_closeAuditStream
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
