VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202508.03.0"
  config.vm.hostname = "ubuntu-spade-2404"
  config.vm.network "private_network", ip: "192.168.2.3" , netmask: "255.255.255.0"
  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", "32768"]
    v.customize ["modifyvm", :id, "--cpus", 16]
  end

  config.vm.provision "shell", privileged:false, inline: <<-SHELL

    # Install Java
    sudo add-apt-repository -y ppa:openjdk-r/ppa
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk

    # Install SPADE
    sudo apt-get install -y auditd bison clang cmake curl flex fuse git ifupdown libaudit-dev libfuse-dev linux-headers-`uname -r` lsof pkg-config unzip uthash-dev wget
    git clone https://github.com/ashish-gehani/SPADE.git
    cd SPADE
    ./configure
    make
    ./bin/allowAuditAccess

  SHELL
end
