/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package spade.storage.kafka;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Vertex extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Vertex\",\"namespace\":\"spade.storage.kafka\",\"fields\":[{\"name\":\"annotations\",\"type\":[\"null\",{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}]},{\"name\":\"hash\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.Map<java.lang.String,java.lang.String> annotations;
  @Deprecated public java.lang.String hash;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Vertex() {}

  /**
   * All-args constructor.
   */
  public Vertex(java.util.Map<java.lang.String,java.lang.String> annotations, java.lang.String hash) {
    this.annotations = annotations;
    this.hash = hash;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return annotations;
    case 1: return hash;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: annotations = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    case 1: hash = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'annotations' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getAnnotations() {
    return annotations;
  }

  /**
   * Sets the value of the 'annotations' field.
   * @param value the value to set.
   */
  public void setAnnotations(java.util.Map<java.lang.String,java.lang.String> value) {
    this.annotations = value;
  }

  /**
   * Gets the value of the 'hash' field.
   */
  public java.lang.String getHash() {
    return hash;
  }

  /**
   * Sets the value of the 'hash' field.
   * @param value the value to set.
   */
  public void setHash(java.lang.String value) {
    this.hash = value;
  }

  /** Creates a new Vertex RecordBuilder */
  public static spade.storage.kafka.Vertex.Builder newBuilder() {
    return new spade.storage.kafka.Vertex.Builder();
  }
  
  /** Creates a new Vertex RecordBuilder by copying an existing Builder */
  public static spade.storage.kafka.Vertex.Builder newBuilder(spade.storage.kafka.Vertex.Builder other) {
    return new spade.storage.kafka.Vertex.Builder(other);
  }
  
  /** Creates a new Vertex RecordBuilder by copying an existing Vertex instance */
  public static spade.storage.kafka.Vertex.Builder newBuilder(spade.storage.kafka.Vertex other) {
    return new spade.storage.kafka.Vertex.Builder(other);
  }
  
  /**
   * RecordBuilder for Vertex instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Vertex>
    implements org.apache.avro.data.RecordBuilder<Vertex> {

    private java.util.Map<java.lang.String,java.lang.String> annotations;
    private java.lang.String hash;

    /** Creates a new Builder */
    private Builder() {
      super(spade.storage.kafka.Vertex.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(spade.storage.kafka.Vertex.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.annotations)) {
        this.annotations = data().deepCopy(fields()[0].schema(), other.annotations);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hash)) {
        this.hash = data().deepCopy(fields()[1].schema(), other.hash);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Vertex instance */
    private Builder(spade.storage.kafka.Vertex other) {
            super(spade.storage.kafka.Vertex.SCHEMA$);
      if (isValidValue(fields()[0], other.annotations)) {
        this.annotations = data().deepCopy(fields()[0].schema(), other.annotations);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hash)) {
        this.hash = data().deepCopy(fields()[1].schema(), other.hash);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'annotations' field */
    public java.util.Map<java.lang.String,java.lang.String> getAnnotations() {
      return annotations;
    }
    
    /** Sets the value of the 'annotations' field */
    public spade.storage.kafka.Vertex.Builder setAnnotations(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[0], value);
      this.annotations = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'annotations' field has been set */
    public boolean hasAnnotations() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'annotations' field */
    public spade.storage.kafka.Vertex.Builder clearAnnotations() {
      annotations = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'hash' field */
    public java.lang.String getHash() {
      return hash;
    }
    
    /** Sets the value of the 'hash' field */
    public spade.storage.kafka.Vertex.Builder setHash(java.lang.String value) {
      validate(fields()[1], value);
      this.hash = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'hash' field has been set */
    public boolean hasHash() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'hash' field */
    public spade.storage.kafka.Vertex.Builder clearHash() {
      hash = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Vertex build() {
      try {
        Vertex record = new Vertex();
        record.annotations = fieldSetFlags()[0] ? this.annotations : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[0]);
        record.hash = fieldSetFlags()[1] ? this.hash : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
