/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package spade.storage.kafka;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** A generic object which can be either a vertex or an edge */
@org.apache.avro.specific.AvroGenerated
public class GraphElement extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1711306156375975460L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GraphElement\",\"namespace\":\"spade.storage.kafka\",\"doc\":\"A generic object which can be either a vertex or an edge\",\"fields\":[{\"name\":\"element\",\"type\":[{\"type\":\"record\",\"name\":\"Edge\",\"fields\":[{\"name\":\"annotations\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]},{\"name\":\"childVertexHash\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"parentVertexHash\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"hash\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"Vertex\",\"fields\":[{\"name\":\"annotations\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]},{\"name\":\"hash\",\"type\":\"string\"}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Object element;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GraphElement() {}

  /**
   * All-args constructor.
   * @param element The new value for element
   */
  public GraphElement(java.lang.Object element) {
    this.element = element;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return element;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: element = (java.lang.Object)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'element' field.
   * @return The value of the 'element' field.
   */
  public java.lang.Object getElement() {
    return element;
  }

  /**
   * Sets the value of the 'element' field.
   * @param value the value to set.
   */
  public void setElement(java.lang.Object value) {
    this.element = value;
  }

  /**
   * Creates a new GraphElement RecordBuilder.
   * @return A new GraphElement RecordBuilder
   */
  public static spade.storage.kafka.GraphElement.Builder newBuilder() {
    return new spade.storage.kafka.GraphElement.Builder();
  }

  /**
   * Creates a new GraphElement RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GraphElement RecordBuilder
   */
  public static spade.storage.kafka.GraphElement.Builder newBuilder(spade.storage.kafka.GraphElement.Builder other) {
    return new spade.storage.kafka.GraphElement.Builder(other);
  }

  /**
   * Creates a new GraphElement RecordBuilder by copying an existing GraphElement instance.
   * @param other The existing instance to copy.
   * @return A new GraphElement RecordBuilder
   */
  public static spade.storage.kafka.GraphElement.Builder newBuilder(spade.storage.kafka.GraphElement other) {
    return new spade.storage.kafka.GraphElement.Builder(other);
  }

  /**
   * RecordBuilder for GraphElement instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GraphElement>
    implements org.apache.avro.data.RecordBuilder<GraphElement> {

    private java.lang.Object element;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(spade.storage.kafka.GraphElement.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.element)) {
        this.element = data().deepCopy(fields()[0].schema(), other.element);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing GraphElement instance
     * @param other The existing instance to copy.
     */
    private Builder(spade.storage.kafka.GraphElement other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.element)) {
        this.element = data().deepCopy(fields()[0].schema(), other.element);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'element' field.
      * @return The value.
      */
    public java.lang.Object getElement() {
      return element;
    }

    /**
      * Sets the value of the 'element' field.
      * @param value The value of 'element'.
      * @return This builder.
      */
    public spade.storage.kafka.GraphElement.Builder setElement(java.lang.Object value) {
      validate(fields()[0], value);
      this.element = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'element' field has been set.
      * @return True if the 'element' field has been set, false otherwise.
      */
    public boolean hasElement() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'element' field.
      * @return This builder.
      */
    public spade.storage.kafka.GraphElement.Builder clearElement() {
      element = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public GraphElement build() {
      try {
        GraphElement record = new GraphElement();
        record.element = fieldSetFlags()[0] ? this.element : (java.lang.Object) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
